server:
  port: 8762

spring:
  application:
    name: eureka-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/store
    driverClassName: org.postgresql.Driver
    username: root
    password: 123123Aa@
  redis:
    host: redis-17513.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
    port: 17513
    password: rvPHMCGdR5fVup0iZGl0fSqKWwfCHYhH
    prefix-key: 'ndt:'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

ribbon:
  ReadTimeout: 60000 # ms
  ConnectTimeout: 60000 # ms
  eureka:
    enabled: true

zuul:
  ignored-services: "*"
  routes:
    user-service:
      path: /user/**
      service-id: user-service
    admin-service:
      path: /admin/**
      service-id: admin-service
    authenticate-service:
      path: /auth/**
      service-id: authenticate-service

app:
  security:
    key-secret: BB8D76746D8586359AB25E18D5EFB
    expiration-token: 432000000 # ms  : 5 days
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  # s: 1s

  check-spamming-request:
    enable: false
    max-request: 5
    time-for-max-request: 1 #s: 1s
    expiration-time-spamming: 1800 #s: 3600s
