server:
  port: 8762

spring:
  application:
    name: eureka-gateway
  datasource:
    url: jdbc:postgresql://10.1.20.169:5432/intern_2022
    username: postgres
    password: Tdt@6868
  redis:
    host: redis-15714.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
    port: 15714
    password: usyEK86FiprLOYwtzeNgW405iiY8AK68
    prefix-key: 'ndt:'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

ribbon:
  ReadTimeout: 60000 # ms
  ConnectTimeout: 60000 # ms
  eureka:
    enabled: true

zuul:
  ignored-services: "*"
  routes:
    user-service:
      path: /user/**
      service-id: user-service
    admin-service:
      path: /admin/**
      service-id: admin-service
    authenticate-service:
      path: /auth/**
      service-id: authenticate-service

app:
  security:
    key-secret: BB8D76746D8586359AB25E18D5EFB
    expiration-token: 900000 # 15 minutes
