package main.java.common.enums;

import com.tdt.cqsta.common.constants.NumberConstants;
import lombok.Getter;

@Getter
public enum MetaData {
    //Successful responses
    SUCCESS(200, "Success"),
    NO_CONTENT(204, "No Content"),
    UNSAVED_LATER_POST_SUCCESS(2001, "Unsaved later post Success"),
    FAILURE(4050, "Failure"),
    NO_REQUEST_BODY(4761, "Request body is missing"),
    UNSUPPORTED_MEDIA_TYPE(415, "Unsupported media type"),

    //Missing login param
    PARAMETERS_MISSING(4762, "Parameters is missing"),
    USERNAME_MISSING(4763, "Username is missing"),
    PASSWORD_MISSING(4764, "Password is missing"),
    TYPE_MISSING(4765, "Type is missing"),
    GOOGLE_TOKEN_INVALID(4691, "Google token is invalid"),
    FACEBOOK_TOKEN_INVALID(4692, "Facebook token is invalid"),
    LINKEDIN_TOKEN_INVALID(4693, "LinkedIn token is invalid"),
    HASHTAG_MISSING(4766, "Hashtags is missing"),
    DEVICE_ID_INVALID(4694, "Device id is invalid"),
    PASSWORD_FAIL_TOO_MANY_TIMES(4788, "Password failed more than the specified number of times"),
    SEND_REQUEST_TOO_MANY_TIMES(4789, "Send request too many times"),

    //Missing register param
    EMAIL_MISSING(4767, "Email is missing"),
    PHONE_MISSING(4768, "Phone is missing"),
    DISPLAY_NAME_MISSING(4769, "Display Name is missing"),
    DOB_INVALID(4610, "Dob is wrong format"),
    GENDER_INVALID(4611, "Gender is wrong format"),
    PIN_MISSING(4760, "Pin is missing"),
    REPORT_ID_MISSING(4750, "Report id is missing"),
    REPORT_LEVER_MISSING(4751, "Report lever is missing"),
    REPORT_TYPE_MISSING(4752, "Report type is missing"),
    REPORT_TYPE_NOT_FOUND(4801, "Report type is not found"),
    REPORT_LEVER_INVALID(4695, "Report lever is invalid"),
    REPORT_IS_EXIST(4696, "Report is exist"),
    ACTION_INVALID(4697, "Param action is invalid"),
    PIN_ACTION_NOT_EXIST(4555, "Param pin action not exist"),
    DEVICE_ID_MISSING(4753, "Device id is missing"),
    INPUT_ENCODING_DATA_INVALID(4698, "Input encoding data is invalid"),
    REFRESH_TOKEN_IS_MISSING(4099, "Refresh token is missing"),
    TOPIC_NAME_IS_MISSING(4088, "Topic name is missing"),
    POST_IDS_IS_MISSING(4089, "Post ids are missing"),

    //edit profile
    DISPLAY_NAME_REQUIRED(4600, "Display name is required"),
    DOB_REQUIRED(4601, "Dob is required"),
    GENDER_REQUIRED(4602, "Gender is required"),
    EMAIL_REQUIRED(4603, "Email is required"),

    //Register messages
    EMAIL_EXIST(4620, "Email is existed"),
    PHONE_EXIST(4621, "Phone is existed"),
    EMAIL_OR_PHONE_EXIST(4622, "Email or phone number is existed"),
    USERNAME_EXIST(4623, "Username is existed"),
    UUID_INVALID(4681, "Uuid is invalid"),
    EMAIL_NOT_EXIST(4640, "Email does not exist"),
    EMAIL_OR_PHONE_NOT_EXIST(4641, "Email or phone number does not exist"),
    PHONE_NOT_EXIST(4642, "Phone does not exist"),

    EMAIL_INVALID(4612, "Email is invalid"),
    PHONE_INVALID(4613, "Phone number is invalid"),
    PRIVACY_WRONG_FORMAT(4614, "Privacy is wrong format"),
    PIN_INVALID(4682, "Verification code is invalid"),
    PASSWORD_INVALID(4660, "Password must contain at least 8 characters, at least one lowercase letter, one uppercase letter, one numeric digit, and one special character"),
    TYPE_INVALID(4683, "Type is invalid"),
    IMAGE_INVALID(4684, "Image is invalid"),
    LANGUAGE_INVALID(4685, "Language invalid"),
    TITLE_MISSING(4754, "Param title is missing"),
    ONLY_ONE_PARAM_OF_TWO(4010, "Input only one out of two params"),
    PAGE_INVALID(4780, "Param page must be greater than 0"),
    SUB_CMT_ID_INVALID(4686, "Sub comment id invalid"),
    CMT_ID_INVALID(4687, "Comment id invalid"),
    POST_ID_INVALID(4688, "Post id invalid"),
    GROUP_ID_INVALID(4689, "Group id invalid"),
    PAGE_SIZE_INVALID(4781, "Param page_size must be greater than 0"),
    TOKEN_INVALID(4092, "Token invalid"),
    ROLE_INVALID(4782, "Param role is invalid"),
    DATE_INPUT_INVALID(4783, "Param date is invalid"),
    VISIBILITY_INVALID(4784, "Param visibility is invalid"),
    MEMBER_NO_INVALID(4785, "Param memberNo is invalid"),
    REACTION_INVALID(4680, "Reaction invalid"),
    ONLY_NUMBER(4630, "Params allows only number"),
    POST_ID_MISSING(4755, "Post id is missing"),
    APPLY_TO_ALL_MISSING(4756, "Param apply to all is missing"),
    TOKEN_NOTIFICATION_MISSING(4757, "Token notification is missing"),
    FCM_TOKEN_MISSING(4786, "Fcm token is missing"),
    APNS_TOKEN_MISSING(4787, "Apns token is missing"),
    CONTENT_AND_FILE_MISSING(4758, "Content and files are missing"),
    IMAGE_MISSING(4759, "Image is missing"),
    POST_NOT_FOUND(4732, "Post not found"),
    FRIEND_NOT_FOUND(4733, "Friend not found"),
    GROUP_NOT_FOUND(4400, "Group not found"),
    GROUP_ALREADY_PINNED(4701, "Group already pinned"),
    List_FRIEND_EMPTY(2003, "User have no friend"),
    LIST_FRIEND_NOT_MATCH(2004, "List response friend not match"),
    GROUP_ID_MISSING(4740, "Params group_id is missing"),
    LANGUAGE_MISSING(4741, "Language is missing"),
    USER_ID_MISSING(4742, "User id is missing"),
    List_MEMBERS(4743, "List members is missing"),
    NAME_IN_LIST_MISSING(4744, "Param name in list members is missing"),
    USER_ID_IN_LIST_MISSING(4745, "Param user_id in list members is missing"),
    LIST_ID_MISSING(4746, "List id empty or missing"),
    INVITED_ALL_FRIEND(2005, "Invited all friends"),
    LIST_USER_NOT_MATCH(2006, "List memberId and userId not match"),
    REQUEST_BODY_MISSING(4747, "Request body is missing"),
    REQUEST_BODY_INVALID(4690, "Request body is invalid"),
    MEMBER_NOT_EXIST(4643, "Member does not exist"),
    USER_NOT_EXIST(4644, "User does not exist"),
    NOTIFICATION_NOT_EXIST(4645, "Notification does not exist"),
    BLOCKED_USER(4646, "User is being blocked"),
    REQUEST_NOT_EXIST(4850, "User does not have the right permissions"),
    OUT_OF_GROUP_RULES_LIMIT(4001, "Limit rules is " + NumberConstants.DEFAULT_GROUP_RULES_LIMIT),
    RULE_TILE_MISSING(4748, "Rule title is missing"),
    RULE_CONTENT_MISSING(4749, "Rule content is missing"),
    RULE_ID_MISSiNG(4730, "Rule id is missing"),
    RULE_NOT_FOUND(4731, "Rule not found"),
    LIST_RULE_NOT_MATCH(2007, "List rule in DB and in request not match"),
    ACTION_MISSING(4734, "Action is missing"),
    MUTE_TIME_MISSING(4735, "Mute_time is missing"),
    MUTE_ONLY_WITH_ACTION_MUTE(4002, "Mute_time is only with action mute"),
    USER_BLOCKING(4736, "User is blocking"),
    USER_MUTING(4737, "User is muting"),
    USER_PENDING(4738, "User is pending"),
    USER_ACTIVE(4739, "User is active"),
    USER_INVITED(4720, "User is invited"),
    USER_INACTIVE(4721, "User is inactive"),
    STATUS_ONLY_WITH_GROUP_ID(4003, "Param status only with group id"),
    ONLY_ADMIN_SELECT_STATUS(4004, "Only admin can select status"),
    STATUS_INVALID(4722, "status is invalid"),
    SORT_TYPE_INVALID(4800, "Sort type is invalid"),
    SEARCH_STRING_MISSING(4723, "param search string is missing"),
    ONLY_ONE_PARAM_PHONE_OR_EMAIL(4005, "Enter only one phone or email parameter"),
    EMAIL_OR_PHONE_INVALID(4724, "Email or phone invalid"),
    INPUT_PARAM_PHONE_OR_EMAIL(4006, "Must input phone or email parameter"),
    CAN_NOT_HIDE_OWN_POST(4860, "User can not hide their own post"),
    EMAIL_AND_PHONE_MISSING(4725, "Email and phone are missing"),
    EMAIL_PHONE_NUMBER_NEEDS_VERIFICATION(4861, "Email/Phone number needs verification"),
    YOUR_PROFILE_NEEDS_EMAIL_OR_PHONE(4870, "Your profile needs at least an email address or a phone number"),
    POST_PRIVACY_INVALID(4726, "Post privacy invalid"),
    POST_NOTI_INVALID(4727, "Post notification privacy is invalid"),
    POST_APPROVAL_NOTI_INVALID(4728, "Post approval notification privacy is invalid"),
    MEMBER_REQUEST_NOTI_INVALID(4710, "Member request notification privacy is invalid"),
    WHO_CAN_POST_INVALID(4711, "Who can post invalid"),
    SHOW_DOB_FLG_INVALID(4712, "Show dob flg invalid"),
    SHOW_EMAIL_FLG_INVALID(4713, "Show email flg invalid"),
    SHOW_PHONE_FLG_INVALID(4714, "Show phone flg invalid"),
    FRIEND_REQUEST_INVALID(4715, "Friend request invalid"),
    ACTIVITY_TYPE_INVALID(4788, "Activity type invalid"),
    LIMIT_FAVORITE_MEMBER(4007, "Limit favorite member is %s"),
    LIMIT_REPORT_FOR_POST(4016, "Limit report for post is %s"),
    ALREADY_SENT_FRIEND_REQUEST(4871, "You already sent friend request to this user"),
    IS_ENABLE_INVALID(4716, "IsEnable is invalid"),
    THEME_INVALID(4717, "Theme is invalid"),
    CAN_NOT_MUTE_ADMIN(4008, "You do not have rights to do this action"),
    CAN_NOT_HIDDEN_WITH_PUBLIC_GROUPS(4880, "Public groups can only be visible"),
    RESOURCE_ID_IS_MISSING(4718, "Resource_id is missing"),
    CAN_NOT_CHANGE_PRIVACY(4790, "Can not change privacy of group with private groups"),
    MAX_FRIEND_IS_MISSING(4791, "Field max friend is missing"),
    MAX_FAVORITE_IS_MISSING(4792, "Field max favorite is missing"),
    MAX_FOLLOWER_IS_MISSING(4793, "Field max follower is missing"),
    MAX_FOLLOWING_IS_MISSING(4794, "Field max following is missing"),
    MAX_REPORT_NUMBER_IS_MISSING(4795, "Field max report number is missing"),
    MAX_LOGIN_FAIL(4796, "Field max login fail is missing"),
    TERM_OF_USE_IS_MISSING(4797, "Term of use is missing"),
    PRIVACY_POLICY_IS_MISSING(4798, "Privacy policy is missing"),
    DESCRIPTION_MISSING(4799, "Param description is missing"),
    TEMPLATE_MISSING(4881, "Param template is missing"),
    NOTI_TIME_INVALID(4882, "Param noti_time is invalid"),
    TEAM_NOT_FOUND(4883, "Team not found"),
    CHANNEL_NOT_FOUND(4499, "Channel not found"),
    FIELD_NAME_IS_MISSING(4886, "Field name is missing"),
    FIELD_TYPE_IS_MISSING(4884, "Field type is missing"),
    TEAM_ID_IS_MISSING(4885, "Field team_Id is missing"),
    CHANNEL_ID_INVALID(4887, "Channel_id is invalid"),
    SCHEME_MEMBER_INVALID(4888, "Scheme_admin and/or scheme_user is invalid"),
    MESSAGE_AND_FILE_IDS_CANNOT_EMPTY(4889, "Message and FileIds cannot be empty at the same time"),
    REASONS_FIELD_IS_MISSING(4899, "Reason field is missing"),
    GIFS_ID_IS_MISSING(4897, "Gifs_id is missing"),
    GIFS_NOT_FOUND(4898, "Gif is not found"),

    //OTP messages
    NOT_VERIFIED(4009, "You have not entered the OTP"),
    NOT_VERIFIED_REGISTER(4719, "OTP is missing"),


    SEND_OTP_FAILED(4729, "Failed to send OTP"),

    // Redirection messagesY
    MULTIPLE_CHOICE(300, "Multiple Choice"),

    BAD_CREDENTIALS(301, "Bad Credentials"),

    // Client error responses
    BAD_REQUEST(400, "Bad request"),
    HTTP_MEDIA_TYPE_NOT_SUPPORTED(4010, "Http Media Type Not Supported"),
    HTTP_CONTENT_TYPE_IS_UNKNOWN(4023, "Http Content Type is Unknown"),
    MAX_UPLOAD_SIZE_EXCEEDED_EXCEPTION(4890, "Reached maximum file size %s"),
    MISSING_SERVLET_REQUEST_PART(4011, "Missing Servlet Request Part"),
    MISSING_REQUEST_HEADER(4110, "Missing Request Header"),
    MULTIPART_IS_NULL(4012, "Param invalid"),
    MISSING_CONTENT_POST(4013, "Content of Post is null or empty"),
    MISSING_TOPIC_POST(4014, "Topic of Post is missing"),
    TOPIC_POST_INVALID(4015, "Topic of Post is invalid"),
    UNAUTHORIZED(401, "Unauthorized"),
    ALREADY_EXISTED_POST_ID(4017, "Already existed post id"),
    PAYMENT_REQUIRED(402, "Payment Required"),
    FORBIDDEN(403, "Forbidden"),
    NOT_FOUND(404, "Not Found"),
    METHOD_NOT_ALLOWED(405, "Method Not Allowed"),
    ACTION_NOT_ALLOWED(406, "Action Not Allowed"),
    REQUEST_TIMEOUT(408, "Request Timeout"),
    TOKEN_EXPIRED(4018, "Token expired"),
    ACCESS_DENIED(4810, "Access is denied"),
    YOU_DO_NOT_HAVE_RIGHTS(4019, "You do not have rights to do this action"),
    MISSING_POST_ID(4021, "Missing post id"),
    PASSING_WRONG_PARAMS(4022, "Cannot passing both group_Id and destination_id"),
    PASSWORD_INCORRECT(4090, "Login password is incorrect"),
    USERNAME_OR_PASSWORD_INCORRECT(4100, "Incorrect username or password."),
    PASSWORD_ALREADY_USED(4091, "The new password is the same as one of your three previous passwords. Please enter a new ones"),
    EXCEED_MAX_LENGTH_CONTENT_POST(4094, "The content of post exceed %s characters"),
    EXCEED_MAX_LENGTH_COMMENT_POST(4095, "The comment of post exceed %s characters"),
    EXCEED_MAX_LENGTH_GROUP_NAME(4096, "The name of group exceed %s characters"),
    EXCEED_MAX_LENGTH_GROUP_DESCRIPTION(4097, "The description of group exceed %s characters"),
    EXCEED_MAX_NUMBER_FILE_OF_POST(4098, "The number file of post exceed %s file"),
    YOU_OR_OTHER_PERSON_HAS_LIMITED_FRIENDS(4896, "You or Other person has limited friends"),

    // Group message
    GROUP_NAME_REQUIRED(4011, "Group name Required"),
    GROUP_PRIVACY_REQUIRED(4615, "Group privacy is wrong format"),
    GROUP_VISIBLE_REQUIRED(4616, "Group visible is wrong format"),
    GROUP_RIGHT_TO_POST_REQUIRED(4617, "Group right to post is wrong format"),
    GROUP_POST_APPROVAL_REQUIRED(4618, "Approval member request is wrong format"),
    POST_PRIVACY_REQUIRED(4012, "Post privacy Required"),
    STATUS_MISSING(4770, "Status is missing"),
    RESOURCE_IS_MISSING(4771, "Missing resource"),
    UPLOAD_ONE_GIF_FILE(4702, "Must upload only 1 Gif file"),
    UPLOAD_NOT_GIF_FILE(4703, "Is not a Gif file"),
    GIF_NOT_FOUND(4704, "Gif not found"),
    POEM_USER_CATEGORY_CD_INVALID(4705, "Poem user's category_cd is invalid"),
    POEM_USER_SELF_AE_CD_EMPTY(4706, "Poem user's self_ae_cd is empty"),
    POEM_USER_SELF_AE_CD_EXISTS(4707, "Poem user's self_ae_cd is exists"),
    ROLE_MISSING(4772, "Role is missing"),
    IS_ADMIN_MISSiNG(4773, "Is_admin is missing"),
    USER_ID_MISSiNG(4774, "User id is missing"),
    ACTION_MISSiNG(4775, "Param action is missing"),
    LIST_USER_ID_EMPTY(4776, "User id list is empty"),
    ONE_OR_MORE_USERS_INVALID(4777, "One or more invalid users exits"),
    PLATFORM_INVALID(4778, "Platform is invalid"),
    LIST_TAG_PEOPLE_INVALID(4779, "The list of people tagged is not valid"),
    MODULE_INVALID(4894, "Module is invalid"),
    PERMISSION_INVALID(4895, "Permission is invalid"),
    NOT_ADMIN(4851, "User does not have the right permissions"),
    NOT_PERMISSION(4852, "User does not have the right permissions"),
    UPDATE_MEMBER(4891, "Unable to add this member as a Admin"),
    GROUP_PRIVACY_INVALID(4709, "Group privacy invalid"),
    GROUPS_EMPTY(4708, "Groups is empty"),
    // CQTV meta message
    VIDEO_NOT_EXISTS(4892, "Video not exists"),
    COMMENT_NOT_EXISTS(4893, "Comment not exists"),
    NOT_PERMISSION_EDIT_CQTV(4900, "You can only edit your video"),

    POINTS_HISTORY_NOT_FOUND(4901, "Points History not found"),

    // Server error responses
    INTERNAL_SERVER_ERROR(500, "Internal Server Error"),
    BAD_GATEWAY(502, "Bad Gateway"),
    SERVICE_UNAVAILABLE(503, "Service Unavailable"),
    GATEWAY_TIMEOUT(504, "Gateway Timeout"),

    // Voucher meta message
    VOUCHER_NAME_IS_NULL(4902, "Voucher name can't be null"),
    VOUCHER_IMAGE_IS_NULL(4903, "Voucher image can't be null"),
    POINT_TO_EXCHANGE_IS_NULL(4904, "Point to exchange can't be null"),
    NUMBER_AVAILABLE_VOUCHER_IS_NULL(4905, "Number available voucher can't be null"),
    START_DATE_IS_NULL(4906, "Start date can't be null"),
    EXPIRE_DATE_IS_NULL(4907, "Expire date can't be null"),
    DATE_VOUCHER_WRONG_FORMAT(4908, "Expire date or start date wrong format"),
    LEVEL_MISSING(4909, "Level is missing"),
    START_POINT_MISSING(4910, "Start point is missing"),
    END_POINT_MISSING(4911, "End point is missing"),
    POINT_INVALID(4912, "Start point must more less end point"),
    VOUCHER_NOT_FOUND(4950, "Voucher does not exist"),
    NOT_ENOUGH_POINTS_TO_EXCHANGE(4913, "You don't have enough points to redeem"),
    VOUCHER_EXIST_IN_YOUR_LIST(4914, "Voucher exist in your list"),
    VOUCHER_SOLD_OUT(4915, "Voucher is sold out"),
    VOUCHER_CODE_IS_NULL(4916, "Voucher code can't be null"),
    VOUCHER_CODE_IS_EXIST(4917, "Voucher code is existed"),
    START_DATE_IS_AFTER_EXPIRE_DATE(4918, "Start date can't after expire date"),
    VOUCHER_CAN_NOT_REOPEN(4919, "Can't reopen voucher if voucher not expire or not full user redeem"),
    CAN_NOT_CONVERT_DATE_TO_INSTANT(4920, "Can't convert date to instant"),
    GROUP_OWNER_SELF_AE_CD_IS_NULL(4921, "Group Owner Self Ae Cd can't be null"),
    USER_ALREADY_HAS_LMS_ACCOUNT(4922, "User already has cq-lms account"),
    USER_DOES_NOT_HAVE_AN_LMS_ACCOUNT(4923, "User does not have an LMS account"),
    ACCOUNT_ALREADY_LINKED(4924, "This lms account has been linked to another cq-station account"),
    LOGIN_TYPE_INVALID(4925, "Login type invalid"),
    AUTO_LOGIN_LMS_FAILED(4926, "Auto login lms failed, please login again"),
    LMS_USER_ID_NOT_FOUND(4927, "Lms user id is not found"),
    COURSE_ID_INVALID(4928, "Course Id invalid"),
    VERSION_IOS_IS_MISSING(4929, "Version ios is missing"),
    VERSION_ANDROID_IS_MISSING(4930, "Version android is missing"),
    VERSION_WEB_IS_MISSING(4931, "Version web is missing"),
    CREATE_ACCOUNT_FAILED(4932, "Create Cq-learning account failed"),
    PAYMENT_METHOD_ID_EMPTY(4933, "payment_method_id is empty"),
    INVOICE_ID_EMPTY(4934, "invoice_id is empty"),
    MAX_PRICE_OR_MIN_PRICE_INVALID(4935, "Max price or min price is invalid"),
    NUMBER_RATTING_INVALID(4936, "Number ratting is invalid"),
    COMMENT_IS_MISSING(4937, "Comment is missing"),
    UNABLE_TO_SEND_COMPLETION_REPORT(4938, "Unable to send completion report"),
    RATING_ALREADY_EXIST(4939, "Rating already exist from this user"),
    COMMENT_ID_INVALID(4940, "Comment_id is invalid"),
    UNABLE_RATING_COURSE(4941, "Users need to complete the course first"),
    VOUCHER_EXPIRED(4942, "Voucher expired"),
    USER_VOUCHER_NOT_FOUND(4943, "User voucher not found"),
    EXPIRE_DATE_IS_INVALID(4944, "Expiration date can't be before current date"),
    POEM_USER_LIST_OF_TR_CODES_INVALID(4945, "Poem user's list_of_tr_codes is invalid"),
    REPORT_IS_NOT_EXIST(4946, "Report is not exist"),
    REPORT_CATEGORY_IS_INVALID(4947, "Report category is invalid"),
    CAN_NOT_HIDE_OR_UNHIDE_OWN_COMMENT(4948, "Can not hide or un-hide own comment"),
    ALREADY_HIDDEN_THIS_COMMENT(4949, "You already hidden this comment"),
    CAN_NOT_UNHIDE_THIS_COMMENT(4950, "You can not unHidden this comment"),
    SUB_COMMENT_NOT_EXISTS(4951, "Sub comment not exists"),
    CAN_NOT_BLOCK_YOURSELF(4952, "You can not block your-self");

    private final Integer metaCode;
    private final String message;

    MetaData(Integer metaCode, String message) {
        this.metaCode = metaCode;
        this.message = message;
    }

}
